### ISSUE TITLE
"TRACK 01 AUDIO" instead of "TRACK 02 AUDIO".

### ISSUE THREAD

**Issue by bslenul** [nielsbuus/psx_cue_maker_desktop#1]
Hi!

First thing, thank you for [this](http://nielsbuus.dk/pg/psx_cue_maker/), it helped me multiple times :D

I tried your desktop app but sadly I got an error message while trying to mount the .cue file so I checked the content and yeah there's something wrong with it, the first audio track should be `TRACK 02 AUDIO`, not `TRACK 01 AUDIO`. It also shifts the rest of the track (so track 3 becomes track 2, track 4 -> track 3, etc.).

Example with Sled Storm, when using your website the .cue is perfectly fine:
```
FILE "Sled Storm (USA) (Track 01).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "Sled Storm (USA) (Track 02).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 03).bin" BINARY
  TRACK 03 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 04).bin" BINARY
  TRACK 04 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 05).bin" BINARY
  TRACK 05 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 06).bin" BINARY
  TRACK 06 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 07).bin" BINARY
  TRACK 07 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 08).bin" BINARY
  TRACK 08 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 09).bin" BINARY
  TRACK 09 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 10).bin" BINARY
  TRACK 10 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 11).bin" BINARY
  TRACK 11 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
```
and when using the desktop app:
```
FILE "Sled Storm (USA) (Track 01).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "Sled Storm (USA) (Track 02).bin" BINARY
  TRACK 01 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 03).bin" BINARY
  TRACK 02 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 04).bin" BINARY
  TRACK 03 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 05).bin" BINARY
  TRACK 04 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 06).bin" BINARY
  TRACK 05 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 07).bin" BINARY
  TRACK 06 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 08).bin" BINARY
  TRACK 07 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 09).bin" BINARY
  TRACK 08 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 10).bin" BINARY
  TRACK 09 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
FILE "Sled Storm (USA) (Track 11).bin" BINARY
  TRACK 10 AUDIO
   INDEX 00 00:00:00
   INDEX 01 00:02:00
```

Also a quick suggestion: you should upload a release to make it more user friendly! I tried the `PSXCueMaker-Release-Win32-64bit.exe` in \dist but got some lib errors (`libstdc++-6.dll` and `libgcc_s_seh-1.dll`), I ended up installing Mingw-w64 to compile it.

Anyway, thank you again for this helpful tool and have a nice day!

**Comment by nielsbuus** [comment]
Hello @bslenul 

Thanks for your interest in PSX Cue Maker. :-)

The desktop version of PSX Cue Maker is actually written by my friend @clausjensbymadsen. It seems like he accidentally pushed an incomplete debug version into the `dist` folder when he pushed the port to GitHub, which explains the dependencies and also the bug.

Claus has pushed a new binary now. On his behalf, I hope you'll check it out and report back if you have any issues with it.

**Comment by bslenul** [comment]
That was quick! :D 

Well @clausjensbymadsen, your fix worked like a charm, no dependencies issue anymore and the .cue file looks perfectly fine!

Thank you to you two!

**Comment by clausjensbymadsen** [comment]
You're welcome.

I'll close the issue then.
